### ISSUE TITLE
Delete this repo?

### ISSUE THREAD

**Issue by codificat** [thoth-station/website#1]
The website is actually at https://github.com/thoth-station/thoth-station.github.io, so this repo should probably be deleted, right?

Alternatively, update the readme to point to the real repo and archive this one?

**Comment by fridex** [comment]
> The website is actually at https://github.com/thoth-station/thoth-station.github.io, so this repo should probably be deleted, right?

Looks like that. There is also https://github.com/thoth-station/website-tooling/

I'll archive this one and we can eventually remove it after some time.
